import { createServer } from 'node:http'
import { parse as parseUrl } from 'node:url'
import postgres from 'postgres'

const PORT = Number(process.env.PORT || 3001)
const DATABASE_URL = process.env.DATABASE_URL
const ALLOWED_ORIGIN = process.env.ALLOWED_ORIGIN || '*'

if (!DATABASE_URL) {
  throw new Error('DATABASE_URL is required')
}

const sql = postgres(DATABASE_URL, {
  max: 5,
  idle_timeout: 20,
  connect_timeout: 10,
})

async function ensureSchema() {
  await sql`
    create table if not exists dashboard_forward_work_state (
      dev_key text not null,
      item_key text not null,
      status text not null,
      notes text not null default '',
      project_type text,
      sprint_start_date date,
      sprint_end_date date,
      updated_at timestamptz not null default now(),
      updated_by text,
      primary key (dev_key, item_key)
    )
  `

  await sql`alter table dashboard_forward_work_state add column if not exists project_type text`
  await sql`alter table dashboard_forward_work_state add column if not exists sprint_start_date date`
  await sql`alter table dashboard_forward_work_state add column if not exists sprint_end_date date`

  await sql`
    create table if not exists dashboard_forward_work_order (
      dev_key text not null,
      item_key text not null,
      position integer not null,
      updated_at timestamptz not null default now(),
      updated_by text,
      primary key (dev_key, item_key)
    )
  `

  await sql`
    create table if not exists dashboard_runsheet_entries (
      id bigserial primary key,
      project_slug text not null,
      entry_text text not null,
      created_at timestamptz not null default now(),
      created_by text,
      deleted_at timestamptz
    )
  `

  await sql`create index if not exists idx_dashboard_runsheet_entries_project on dashboard_runsheet_entries (project_slug, created_at desc)`

  await sql`
    create table if not exists dashboard_release_notes (
      id bigserial primary key,
      dev_key text not null,
      title text not null,
      body text not null,
      source_item_key text,
      source_url text,
      auto_generated boolean not null default false,
      exceptions text not null default '',
      created_at timestamptz not null default now(),
      created_by text,
      updated_at timestamptz,
      updated_by text,
      deleted_at timestamptz
    )
  `

  await sql`create index if not exists idx_dashboard_release_notes_dev on dashboard_release_notes (dev_key, created_at desc)`

  await sql`alter table dashboard_release_notes add column if not exists source_item_key text`
  await sql`alter table dashboard_release_notes add column if not exists source_url text`
  await sql`alter table dashboard_release_notes add column if not exists auto_generated boolean not null default false`
  await sql`alter table dashboard_release_notes add column if not exists exceptions text not null default ''`
  await sql`alter table dashboard_release_notes add column if not exists updated_at timestamptz`
  await sql`alter table dashboard_release_notes add column if not exists updated_by text`
}

function sendJson(res, status, body) {
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'Access-Control-Allow-Origin': ALLOWED_ORIGIN,
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
  })
  res.end(JSON.stringify(body))
}

function sendEmpty(res, status = 204) {
  res.writeHead(status, {
    'Access-Control-Allow-Origin': ALLOWED_ORIGIN,
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET,POST,PUT,DELETE,OPTIONS',
  })
  res.end()
}

async function readBody(req) {
  const chunks = []
  for await (const chunk of req) chunks.push(chunk)
  if (chunks.length === 0) return {}
  const raw = Buffer.concat(chunks).toString('utf8')
  return raw ? JSON.parse(raw) : {}
}

function normalizeDateOnly(value) {
  if (!value) return null
  if (typeof value === 'string') return value.slice(0, 10)
  return new Date(value).toISOString().slice(0, 10)
}

function normalizeRow(row) {
  return {
    status: row.status,
    notes: row.notes || '',
    projectType: row.project_type || null,
    sprintStartDate: normalizeDateOnly(row.sprint_start_date),
    sprintEndDate: normalizeDateOnly(row.sprint_end_date),
    updated: row.updated_at ? new Date(row.updated_at).getTime() : null,
    updatedBy: row.updated_by || null,
  }
}

function normalizeRunsheet(row) {
  return {
    id: String(row.id),
    ts: new Date(row.created_at).getTime(),
    text: row.entry_text,
    by: row.created_by || null,
  }
}

function normalizeReleaseNote(row) {
  return {
    id: String(row.id),
    devKey: row.dev_key,
    title: row.title,
    body: row.body,
    sourceItemKey: row.source_item_key || null,
    sourceUrl: row.source_url || null,
    autoGenerated: Boolean(row.auto_generated),
    exceptions: row.exceptions || '',
    ts: new Date(row.created_at).getTime(),
    by: row.created_by || null,
  }
}

async function handleGetForwardWork(devKey, res) {
  const [stateRows, orderRows] = await Promise.all([
    sql`select item_key, status, notes, project_type, sprint_start_date, sprint_end_date, updated_at, updated_by from dashboard_forward_work_state where dev_key = ${devKey}`,
    sql`select item_key from dashboard_forward_work_order where dev_key = ${devKey} order by position asc`,
  ])

  const state = Object.fromEntries(stateRows.map(row => [row.item_key, normalizeRow(row)]))
  const order = orderRows.map(row => row.item_key)
  sendJson(res, 200, { state, order })
}

async function handlePutForwardWork(devKey, itemKey, req, res) {
  const body = await readBody(req)
  const status = typeof body.status === 'string' ? body.status : 'Not started'
  const notes = typeof body.notes === 'string' ? body.notes : ''
  const projectType = typeof body.projectType === 'string' && body.projectType.trim() ? body.projectType.trim() : null
  const sprintStartDate = typeof body.sprintStartDate === 'string' && body.sprintStartDate.trim() ? body.sprintStartDate.trim() : null
  const sprintEndDate = typeof body.sprintEndDate === 'string' && body.sprintEndDate.trim() ? body.sprintEndDate.trim() : null
  const updatedBy = typeof body.updatedBy === 'string' ? body.updatedBy : null

  const [row] = await sql`
    insert into dashboard_forward_work_state (dev_key, item_key, status, notes, project_type, sprint_start_date, sprint_end_date, updated_at, updated_by)
    values (${devKey}, ${itemKey}, ${status}, ${notes}, ${projectType}, ${sprintStartDate}, ${sprintEndDate}, now(), ${updatedBy})
    on conflict (dev_key, item_key)
    do update set
      status = excluded.status,
      notes = excluded.notes,
      project_type = excluded.project_type,
      sprint_start_date = excluded.sprint_start_date,
      sprint_end_date = excluded.sprint_end_date,
      updated_at = now(),
      updated_by = excluded.updated_by
    returning status, notes, project_type, sprint_start_date, sprint_end_date, updated_at, updated_by
  `

  sendJson(res, 200, normalizeRow(row))
}

async function handlePutForwardOrder(devKey, req, res) {
  const body = await readBody(req)
  const order = Array.isArray(body.order) ? body.order.filter(value => typeof value === 'string') : []
  const updatedBy = typeof body.updatedBy === 'string' ? body.updatedBy : null

  await sql.begin(async tx => {
    await tx`delete from dashboard_forward_work_order where dev_key = ${devKey}`
    for (let i = 0; i < order.length; i += 1) {
      await tx`
        insert into dashboard_forward_work_order (dev_key, item_key, position, updated_at, updated_by)
        values (${devKey}, ${order[i]}, ${i}, now(), ${updatedBy})
      `
    }
  })

  sendJson(res, 200, { ok: true })
}

async function handleGetRunsheet(projectSlug, res) {
  const rows = await sql`
    select id, project_slug, entry_text, created_at, created_by
    from dashboard_runsheet_entries
    where project_slug = ${projectSlug}
      and deleted_at is null
    order by created_at desc
  `
  sendJson(res, 200, rows.map(normalizeRunsheet))
}

async function handlePostRunsheet(projectSlug, req, res) {
  const body = await readBody(req)
  const text = typeof body.text === 'string' ? body.text.trim() : ''
  const createdBy = typeof body.createdBy === 'string' ? body.createdBy : null
  if (!text) return sendJson(res, 400, { error: 'text is required' })

  const [row] = await sql`
    insert into dashboard_runsheet_entries (project_slug, entry_text, created_by)
    values (${projectSlug}, ${text}, ${createdBy})
    returning id, project_slug, entry_text, created_at, created_by
  `

  sendJson(res, 201, normalizeRunsheet(row))
}

async function handleDeleteRunsheet(entryId, res) {
  await sql`update dashboard_runsheet_entries set deleted_at = now() where id = ${entryId}`
  sendEmpty(res)
}

async function handleGetReleaseNotes(devKey, res) {
  const rows = await sql`
    select id, dev_key, title, body, source_item_key, source_url, auto_generated, exceptions, created_at, created_by
    from dashboard_release_notes
    where dev_key = ${devKey}
      and deleted_at is null
    order by created_at desc
  `
  sendJson(res, 200, rows.map(normalizeReleaseNote))
}

async function handlePostReleaseNote(devKey, req, res) {
  const body = await readBody(req)
  const title = typeof body.title === 'string' ? body.title.trim() : ''
  const noteBody = typeof body.body === 'string' ? body.body.trim() : ''
  const createdBy = typeof body.createdBy === 'string' ? body.createdBy : null
  const sourceItemKey = typeof body.sourceItemKey === 'string' ? body.sourceItemKey : null
  const sourceUrl = typeof body.sourceUrl === 'string' ? body.sourceUrl : null
  const autoGenerated = Boolean(body.autoGenerated)
  const exceptions = typeof body.exceptions === 'string' ? body.exceptions : ''
  if (!title || !noteBody) return sendJson(res, 400, { error: 'title and body are required' })

  const [row] = await sql`
    insert into dashboard_release_notes (dev_key, title, body, source_item_key, source_url, auto_generated, exceptions, created_by)
    values (${devKey}, ${title}, ${noteBody}, ${sourceItemKey}, ${sourceUrl}, ${autoGenerated}, ${exceptions}, ${createdBy})
    returning id, dev_key, title, body, source_item_key, source_url, auto_generated, exceptions, created_at, created_by
  `

  sendJson(res, 201, normalizeReleaseNote(row))
}

async function handlePatchReleaseNote(entryId, req, res) {
  const body = await readBody(req)
  const title = typeof body.title === 'string' ? body.title.trim() : ''
  const noteBody = typeof body.body === 'string' ? body.body.trim() : ''
  const updatedBy = typeof body.updatedBy === 'string' ? body.updatedBy : null
  const exceptions = typeof body.exceptions === 'string' ? body.exceptions : ''
  if (!title || !noteBody) return sendJson(res, 400, { error: 'title and body are required' })

  const [row] = await sql`
    update dashboard_release_notes
    set title = ${title},
        body = ${noteBody},
        exceptions = ${exceptions},
        updated_at = now(),
        updated_by = ${updatedBy}
    where id = ${entryId}
    returning id, dev_key, title, body, source_item_key, source_url, auto_generated, exceptions, created_at, created_by
  `

  if (!row) return sendJson(res, 404, { error: 'Not found' })
  sendJson(res, 200, normalizeReleaseNote(row))
}

async function handleDeleteReleaseNote(entryId, res) {
  await sql`update dashboard_release_notes set deleted_at = now() where id = ${entryId}`
  sendEmpty(res)
}

const server = createServer(async (req, res) => {
  try {
    if (req.method === 'OPTIONS') return sendEmpty(res)

    const { pathname = '/' } = parseUrl(req.url || '/', true)

    if (req.method === 'GET' && pathname === '/health') {
      return sendJson(res, 200, { ok: true })
    }

    const forwardMatch = pathname.match(/^\/api\/forward-work\/([^/]+)$/)
    if (req.method === 'GET' && forwardMatch) {
      return await handleGetForwardWork(decodeURIComponent(forwardMatch[1]), res)
    }

    const orderMatch = pathname.match(/^\/api\/forward-work\/([^/]+)\/order$/)
    if (req.method === 'PUT' && orderMatch) {
      return await handlePutForwardOrder(decodeURIComponent(orderMatch[1]), req, res)
    }

    const rowMatch = pathname.match(/^\/api\/forward-work\/([^/]+)\/([^/]+)$/)
    if (req.method === 'PUT' && rowMatch) {
      return await handlePutForwardWork(decodeURIComponent(rowMatch[1]), decodeURIComponent(rowMatch[2]), req, res)
    }

    const runsheetMatch = pathname.match(/^\/api\/runsheets\/([^/]+)$/)
    if (req.method === 'GET' && runsheetMatch) {
      return await handleGetRunsheet(decodeURIComponent(runsheetMatch[1]), res)
    }

    const runsheetEntryMatch = pathname.match(/^\/api\/runsheets\/([^/]+)\/entries$/)
    if (req.method === 'POST' && runsheetEntryMatch) {
      return await handlePostRunsheet(decodeURIComponent(runsheetEntryMatch[1]), req, res)
    }

    const runsheetDeleteMatch = pathname.match(/^\/api\/runsheets\/[^/]+\/entries\/([^/]+)$/)
    if (req.method === 'DELETE' && runsheetDeleteMatch) {
      return await handleDeleteRunsheet(runsheetDeleteMatch[1], res)
    }

    const releaseNotesMatch = pathname.match(/^\/api\/release-notes\/([^/]+)$/)
    if (req.method === 'GET' && releaseNotesMatch) {
      return await handleGetReleaseNotes(decodeURIComponent(releaseNotesMatch[1]), res)
    }

    const releaseNotesCreateMatch = pathname.match(/^\/api\/release-notes\/([^/]+)\/entries$/)
    if (req.method === 'POST' && releaseNotesCreateMatch) {
      return await handlePostReleaseNote(decodeURIComponent(releaseNotesCreateMatch[1]), req, res)
    }

    const releaseNotesDeleteMatch = pathname.match(/^\/api\/release-notes\/[^/]+\/entries\/([^/]+)$/)
    if (req.method === 'DELETE' && releaseNotesDeleteMatch) {
      return await handleDeleteReleaseNote(releaseNotesDeleteMatch[1], res)
    }

    const releaseNotesPatchMatch = pathname.match(/^\/api\/release-notes\/[^/]+\/entries\/([^/]+)$/)
    if (req.method === 'PATCH' && releaseNotesPatchMatch) {
      return await handlePatchReleaseNote(releaseNotesPatchMatch[1], req, res)
    }

    sendJson(res, 404, { error: 'Not found' })
  } catch (error) {
    console.error(error)
    sendJson(res, 500, { error: 'Internal server error' })
  }
})

await ensureSchema()

server.listen(PORT, () => {
  console.log(`project-dashboard-api listening on ${PORT}`)
})
